"""Does the narrator say the vowel house's Swedish names correctly?

The cast in `docs/vowel-house.md` is named in Swedish — Ivar, Åke, Ängla,
Örjan, Ove, Urban — on the principle that a lodger's name starts with the
sound they make. That principle only holds if the name is said the Swedish
way. An English mouth reads *Ivar* as EYE-var, and EYE is the sound of a
completely different lodger, so a mispronounced cast does not merely sound
odd: it teaches the wrong vowel and teaches it by name.

The narration is English, generated by the cloned S2 Pro voice, so the
question is what that voice actually does with these names. This renders
them and leaves the clips somewhere a Swedish speaker can listen.

Run it before authoring lessons that depend on the cast:

    scripts/deck-env/bin/python scripts/tests/probe_cast_names.py OUTDIR
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from lesson_deck.vendor import S2ProVoice, VoiceSpec  # noqa: E402

#: One line per name rather than one line for all of them: a name read inside
#: a list gets list intonation, and the lessons say these names in sentences.
#: The carrier sentence is the shape a lesson actually uses.
LINES: dict[str, str] = {
	"ivar": "The lodger on the roof is called Ivar, and his name starts with the sound he makes.",
	"ake": "The one on the front steps is Åke.",
	"angla": "Ängla stands beside him, two on the step.",
	"orjan": "Put Erik and the basin in the same room and you get Örjan.",
	"ove": "Down in the cellar is Ove.",
	"urban": "Urban lives on the roof, and English has no vowel for him at all.",
	"arnold": "Arnold turns up at the back, and the visit is over.",
	"aina": "Aina and Aino sound the same, and only one of them is ever in the room.",
}


def main(argv: list[str]) -> int:
	if len(argv) != 2:
		print(__doc__)
		return 2

	out = Path(argv[1])
	out.mkdir(parents=True, exist_ok=True)

	voice = S2ProVoice()
	spec = VoiceSpec()
	try:
		for name, line in LINES.items():
			path = out / f"{name}.mp3"
			path.write_bytes(voice.synthesize(line, "en", spec, seed=1))
			print(f"{path}  {line}")
	finally:
		voice.close()

	print(f"\n{len(LINES)} clips in {out}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main(sys.argv))
